apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
  labels:
    app: mariadb-master
spec:
  clusterIP: None
  ports:
  - port: 3306
    name: mariadb-master
  selector:
    app: mariadb-master

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-master
  labels:
    type: glusterfs
    app: mariadb-master
spec:
  storageClassName: gluster-hostpath
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/glusterfs/microk8s/mariadb/mariadb-master"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-master
  labels:
    app: mariadb-master
spec:
  storageClassName: gluster-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-master
  labels:
    app: mariadb-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-master
  template:
    metadata:
      labels:
        app: mariadb-master
    spec:
      hostname: mariadb-master
      volumes:
      - name: mariadb-master
        persistentVolumeClaim:
          claimName: mariadb-master
      containers:
      - name: mariadb-master
        image: "harbor.lan:8443/library/mariadb-custom:11.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-master
          mountPath: /var/lib/mysql
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: MARIADB_PASSWORD
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: MARIADB_REPLICATION_PASSWORD
        - name: MARIADB_USER
          value: databaseuser
        - name: MARIADB_DATABASE
          value: databases
        - name: MARIADB_REPLICATION_USER
          value: replication_user
        args: ["--server_id=1", "--log-bin", "--log-basename=master1", "--binlog-format=mixed"]