apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  labels:
    app: mariadb-slave
spec:
  clusterIP: None
  ports:
  - port: 3306
    name: mariadb-slave
  selector:
    app: mariadb-slave

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-slave
  labels:
    type: local
    app: mariadb-slave
spec:
  storageClassName: local-hostpath
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/microk8s/mariadb/mariadb-slave"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-slave
  labels:
    app: mariadb-slave
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
      
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-slave
  labels:
    app: mariadb-slave
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mariadb-slave
  template:
    metadata:
      labels:
        app: mariadb-slave
    spec:
      hostname: mariadb-slave
      volumes:
      - name: mariadb-slave
        persistentVolumeClaim:
          claimName: mariadb-slave
      containers:
      - name: mariadb-slave
        image: "harbor.lan:8443/library/mariadb-custom:11.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-slave
          mountPath: /var/lib/mysql
        env:
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: MARIADB_REPLICATION_PASSWORD
        - name: MARIADB_MASTER_HOST
          value: mariadb-master
        - name: MARIADB_REPLICATION_USER
          value: replication_user
        - name: MARIADB_HEALTHCHECK_GRANTS
          value: REPLICA MONITOR
        args: ["--log-basename=master1", "--binlog-format=mixed", "--read-only"]